version: 2.0
jobs:
  examples:
    docker:
      - image: gudhi/ci_for_gudhi:latest
    steps:
      - checkout
      - run:
          name: Build and test examples
          command: |
            mkdir build;
            cd build;
            cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUDHI_EXAMPLE=ON -DWITH_GUDHI_TEST=OFF -DWITH_GUDHI_UTILITIES=OFF -DWITH_GUDHI_PYTHON=OFF ..;
            make all;
            ctest --output-on-failure;

  tests:
    docker:
      - image: gudhi/ci_for_gudhi:latest
    steps:
      - checkout
      - run:
          name: Build and test unitary tests
          command: |
            mkdir build;
            cd build;
            cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUDHI_EXAMPLE=OFF -DWITH_GUDHI_TEST=ON -DWITH_GUDHI_UTILITIES=OFF -DWITH_GUDHI_PYTHON=OFF ..;
            make all;
            ctest --output-on-failure;

  utils:
    docker:
      - image: gudhi/ci_for_gudhi:latest
    steps:
      - checkout
      - run:
          name: Build and test utilities
          command: |
            mkdir build;
            cd build;
            cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUDHI_EXAMPLE=OFF -DWITH_GUDHI_TEST=OFF -DWITH_GUDHI_UTILITIES=ON -DWITH_GUDHI_PYTHON=OFF ..;
            make all;
            ctest --output-on-failure;

  python:
    docker:
      - image: gudhi/ci_for_gudhi:latest
    steps:
      - checkout
      - run:
          name: Build and test python module. Generates and tests the python documentation
          command: |
            git submodule init
            git submodule update
            mkdir build;
            cd build;
            cmake -DUSER_VERSION_DIR=version ..;
            make user_version;
            cd version;
            mkdir build;
            cd build;
            cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUDHI_EXAMPLE=OFF -DWITH_GUDHI_UTILITIES=OFF -DWITH_GUDHI_PYTHON=ON -DPython_ADDITIONAL_VERSIONS=3 ..;
            cd python;
            python3 setup.py build_ext --inplace;
            make sphinx;
            cp -R sphinx /tmp/sphinx;
            python3 setup.py install;
            python3 setup.py clean --all;
            python3 -B -m pytest ../../python/test/*.py --cov-report html --cov=gudhi;
            cp -R htmlcov /tmp/htmlcov;

      - store_artifacts:
          path: /tmp/sphinx

      - store_artifacts:
          path: /tmp/htmlcov

  doxygen:
    docker:
      - image: gudhi/ci_for_gudhi:latest
    steps:
      - checkout
      - run:
          name: Generates the C++ documentation with doxygen
          command: |
            git submodule init
            git submodule update
            mkdir build;
            cd build;
            cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUDHI_EXAMPLE=OFF -DWITH_GUDHI_TEST=OFF -DWITH_GUDHI_UTILITIES=OFF -DWITH_GUDHI_PYTHON=OFF -DUSER_VERSION_DIR=version ..;
            make doxygen 2>&1 | tee dox.log;
            grep warning dox.log;
            cp dox.log version/doc/html/;
            cp -R version/doc/html /tmp/doxygen;

      - store_artifacts:
          path: /tmp/doxygen

workflows:
  version: 2
  build:
    jobs:
      - examples
      - tests
      - utils
      - python
      - doxygen
